import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from 'react-hot-toast';
// import SessionWrapper from "@/components/SessionWrapper"; // Direct import of SessionWrapper
import { CookiesProvider } from 'next-client-cookies/server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Neuss HMI ",
  description: "Generated by Neuss HMI",
  icons: "/favicon-32x32.png",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CookiesProvider> {children}</CookiesProvider>
          {/* </SessionWrapper> */}
          <Toaster position="bottom-right"  />
        </ThemeProvider>
      </body>
    </html>
  );
}
